name: "new issues"
description: create a new issue.
title: "VL<nr>-<your issues' title>"
labels: [
  "everything else"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description
      placeholder: ....
    validations:
      required: true
